### PR TITLE
Hop-626 Relook HopVfsFileDialog

### PR DESCRIPTION
**Pull request by nadment**

### CODE REVIEW

**Comment by hansva** [comment]
Tested on my local system and the dialog is no longer working.
Screenshot from 2020-09-28 11-49-15

When I have some spare time I'll see if I can find the root cause

**Comment by nadment** [comment]
I cannot reproduce the problem on windows, need help

**Comment by hansva** [comment]
@nadment, setting the column width seems to be required for linux (or at least gnome). so I remove the comments from that line. could you check if this version still works on your end? and it it does.. feel free to hit merge!

**Comment by nadment** [comment]
Works well with or without column width for me

**Pull request merged**
